In [1]:
import pandas as pd

In [2]:
df_contig=pd.read_csv("/lomi_home/gaoyang/software/CompRanking/test/CompRanking/CompRanking_intermediate/preprocessing/5M_contigs/ERR1191817.contigs_5M_contigs.index",sep="\t",header=None)
df_contig

                  0         1
0            k119_7       1_1
1            k119_8       2_1
2           k119_12       3_1
3           k119_12       3_2
4           k119_14       4_1
...             ...       ...
240330  k119_301780  123145_1
240331  k119_301780  123145_2
240332  k119_301781  123146_1
240333  k119_301781  123146_2
240334  k119_301781  123146_3

[240335 rows x 2 columns]

In [3]:
input_ERR_VFDB_output="/lomi_home/gaoyang/software/CompRanking/test/CompRanking/CompRanking_intermediate/Virulence/ERR1191817.contigs_5M_contigs_VFDB_setA1e-5.out"
df_ERR_VFDB_output=pd.read_csv(input_ERR_VFDB_output,sep="\t",header=None)
df_ERR_VFDB_output.columns=['id', 'sub_id', 'identity', 'alignLen', 'mismat', 'gapOpens', 'qStart', 'qEnd', 'sStart', 'sEnd', 'eval', 'bit']
df_ERR_VFDB_output60= df_ERR_VFDB_output[df_ERR_VFDB_output.identity > 80]
df_ERR_VFDB_output_algn=df_ERR_VFDB_output60[df_ERR_VFDB_output60.alignLen>100]
df_ERR_VFDB_output_algn

,id,sub_id,identity,alignLen,mismat,gapOpens,qStart,qEnd,sStart,sEnd,eval,bit
36,273_2,VFG043206(gb|WP_005164479),91.5,129,11,0,1,129,1,129,5.080000e-82,234.0
50,350_1,VFG038760(gb|WP_016351312),94.5,289,16,0,1,289,56,344,2.100000e-193,531.0
51,350_2,VFG038756(gb|WP_011706626),98.9,275,3,0,1,275,1,275,3.040000e-188,521.0
71,555_1,VFG038679(gb|WP_016350055),86.4,110,15,0,28,137,267,376,1.410000e-63,196.0
123,927_1,VFG049144(gb|WP_002892069),81.3,209,39,0,1,209,717,925,1.060000e-115,350.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14917,121787_2,VFG038587(gb|WP_016349160),91.4,406,35,0,1,406,1,406,2.420000e-263,715.0
14919,121787_4,VFG038581(gb|WP_043118279),90.4,208,20,0,12,219,16,223,9.850000e-136,377.0
14972,122035_1,VFG034721(gb|WP_000556298),87.3,276,35,0,1,276,281,556,1.270000e-184,517.0
14979,122112_1,VFG000924(gb|WP_001234311),100.0,151,0,0,1,151,1,151,9.370000e-100,286.0
15095,122979_1,VFG049018(gb|WP_002913007),95.4,151,7,0,1,151,1,151,1.040000e-99,283.0

In [4]:
#merge
df_VFDB_merge=pd.merge(df_contig,df_ERR_VFDB_output_algn,left_on=1,right_on="id",how="inner")
df_VFDB_merge

,0,1,id,sub_id,identity,alignLen,mismat,gapOpens,qStart,qEnd,sStart,sEnd,eval,bit
0,k119_612,273_2,273_2,VFG043206(gb|WP_005164479),91.5,129,11,0,1,129,1,129,5.080000e-82,234.0
1,k119_816,350_1,350_1,VFG038760(gb|WP_016351312),94.5,289,16,0,1,289,56,344,2.100000e-193,531.0
2,k119_816,350_2,350_2,VFG038756(gb|WP_011706626),98.9,275,3,0,1,275,1,275,3.040000e-188,521.0
3,k119_1303,555_1,555_1,VFG038679(gb|WP_016350055),86.4,110,15,0,28,137,267,376,1.410000e-63,196.0
4,k119_2231,927_1,927_1,VFG049144(gb|WP_002892069),81.3,209,39,0,1,209,717,925,1.060000e-115,350.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,k119_298494,121787_2,121787_2,VFG038587(gb|WP_016349160),91.4,406,35,0,1,406,1,406,2.420000e-263,715.0
530,k119_298494,121787_4,121787_4,VFG038581(gb|WP_043118279),90.4,208,20,0,12,219,16,223,9.850000e-136,377.0
531,k119_299077,122035_1,122035_1,VFG034721(gb|WP_000556298),87.3,276,35,0,1,276,281,556,1.270000e-184,517.0
532,k119_299235,122112_1,122112_1,VFG000924(gb|WP_001234311),100.0,151,0,0,1,151,1,151,9.370000e-100,286.0
533,k119_301371,122979_1,122979_1,VFG049018(gb|WP_002913007),95.4,151,7,0,1,151,1,151,1.040000e-99,283.0

In [5]:
df_VFDB_merge_contigs=df_VFDB_merge[0].unique()
len(df_VFDB_merge_contigs)

465

In [6]:
#保留前3列
df_VFDB_merge=df_VFDB_merge[[0,"id","sub_id"]]
df_VFDB_merge

               0        id                      sub_id
0       k119_612     273_2  VFG043206(gb|WP_005164479)
1       k119_816     350_1  VFG038760(gb|WP_016351312)
2       k119_816     350_2  VFG038756(gb|WP_011706626)
3      k119_1303     555_1  VFG038679(gb|WP_016350055)
4      k119_2231     927_1  VFG049144(gb|WP_002892069)
..           ...       ...                         ...
529  k119_298494  121787_2  VFG038587(gb|WP_016349160)
530  k119_298494  121787_4  VFG038581(gb|WP_043118279)
531  k119_299077  122035_1  VFG034721(gb|WP_000556298)
532  k119_299235  122112_1  VFG000924(gb|WP_001234311)
533  k119_301371  122979_1  VFG049018(gb|WP_002913007)

[534 rows x 3 columns]

In [7]:
#load CompRankingVirluenceSummary
input_cpr_VF_sum="/lomi_home/gaoyang/software/CompRanking/databases/CompRanking_VirulenceDB/CompRanking_Virulence_Summary.csv"
df_cpr_VF_sum=pd.read_csv(input_cpr_VF_sum, index_col=0,sep="\t",header=0)
df_cpr_VF_sum

,VFID,VF_Name,Bacteria,VFCID,VFcategory,ESKAPE,fasID,Virulence_factor
0,VF1338,T6SS secreted effectors,Acinetobacter baumannii,VFC0086,Effector delivery system,Positive,VFG051109(gb|YP_001083177.1),tse1
1,VF1338,T6SS secreted effectors,Acinetobacter baumannii,VFC0086,Effector delivery system,Positive,VFG051110(gb|YP_001083606.1),tse2
2,VF1338,T6SS secreted effectors,Acinetobacter baumannii,VFC0086,Effector delivery system,Positive,VFG051111(gb|YP_001084320.1),tse3
3,VF1338,T6SS secreted effectors,Acinetobacter baumannii,VFC0086,Effector delivery system,Positive,VFG051112(gb|YP_001086354.1),tse4
4,VF0467,Acinetobactin,Acinetobacter baumannii,VFC0272,Nutritional/Metabolic factor,Positive,VFG037218(gb|WP_000983821),basJ
...,...,...,...,...,...,...,...,...
4202,VF0401,Type IV pili,Yersinia pseudotuberculosis,VFC0001,Adherence,Negative,VFG017851(gb|WP_049756370),pilU
4203,VF0401,Type IV pili,Yersinia pseudotuberculosis,VFC0001,Adherence,Negative,VFG017852(gb|WP_011988446),pilU
4204,VF0401,Type IV pili,Yersinia pseudotuberculosis,VFC0001,Adherence,Negative,VFG017853(gb|WP_012105804),pilV
4205,VF0401,Type IV pili,Yersinia pseudotuberculosis,VFC0001,Adherence,Negative,VFG017854(gb|WP_011988482),pilV
4206,VF0623,YPM,Yersinia pseudotuberculosis,VFC0235,Exotoxin,Negative,VFG017885(gb|WP_012105075),ypmA

In [8]:
#merge CompRankingVirluenceSummary and VFDB output
df_VFDB_output_annote=pd.merge(df_VFDB_merge,df_cpr_VF_sum,left_on="sub_id",right_on="fasID",how="left")
df_VFDB_output_annote=df_VFDB_output_annote[[0,"id","sub_id","VFID","Virulence_factor","VF_Name","Bacteria","VFcategory","ESKAPE"]]
df_VFDB_output_annote.columns=["Contigs","id","sub_id","VFID","Virulence_factor","VF_Name","Bacteria","VFcategory","ESKAPE"]
df_VFDB_output_annote

,Contigs,id,sub_id,VFID,Virulence_factor,VF_Name,Bacteria,VFcategory,ESKAPE
0,k119_612,273_2,VFG043206(gb|WP_005164479),VF0394,cheY,Flagella,Yersinia enterocolitica,Motility,Negative
1,k119_816,350_1,VFG038760(gb|WP_016351312),VF0473,flrB,Polar flagella,Aeromonas hydrophila,Motility,Negative
2,k119_816,350_2,VFG038756(gb|WP_011706626),VF0473,flrC,Polar flagella,Aeromonas hydrophila,Motility,Negative
3,k119_1303,555_1,VFG038679(gb|WP_016350055),VF0473,flhB,Polar flagella,Aeromonas hydrophila,Motility,Negative
4,k119_2231,927_1,VFG049144(gb|WP_002892069),VF0568,acrB,AcrAB,Klebsiella pneumoniae,Antimicrobial activity/Competitive advantage,Positive
...,...,...,...,...,...,...,...,...,...
529,k119_298494,121787_2,VFG038587(gb|WP_016349160),VF0477,mshG,MSHA type IV pili,Aeromonas hydrophila,Adherence,Negative
530,k119_298494,121787_4,VFG038581(gb|WP_043118279),VF0477,mshB,MSHA type IV pili,Aeromonas hydrophila,Adherence,Negative
531,k119_299077,122035_1,VFG034721(gb|WP_000556298),VF0237,ibeC,Ibes,Escherichia coli (NMEC),Invasion,Negative
532,k119_299235,122112_1,VFG000924(gb|WP_001234311),VF0228,fepB,Enterobactin,Escherichia coli (UPEC),Nutritional/Metabolic factor,Negative
533,k119_301371,122979_1,VFG049018(gb|WP_002913007),VF0571,rcsB,RcsAB,Klebsiella pneumoniae,Regulation,Positive

In [9]:
# df_VFDB_output_annote.to_csv("/lomi_home/gaoyang/software/CompRanking/test/CompRanking/CompRanking_intermediate/Virulence/CompRanking_Virulence_VFDB_output.csv",sep="\t",index=None)

In [10]:
# #打开利用CPR_DEG10_fiter过的最终结果
# df_CPR_DEG10_fiter_finallResults=pd.read_csv("/lomi_home/gaoyang/software/CompRanking/test/CompRanking/CompRanking_intermediate/Virulence/filterDEG10.csv",sep="\t",header=0,index_col=0)
# df_CPR_DEG10_fiter_finallResults

In [11]:
# #获取VFDB结果中的orfid
# df_VFDB_CPR_DEG10_fiter_finallResults_merge=pd.merge(df_CPR_DEG10_fiter_finallResults,df_VFDB_merge,left_on="ORF_ID",right_on="id",how="inner")
# df_VFDB_CPR_DEG10_fiter_finallResults_merge=df_VFDB_CPR_DEG10_fiter_finallResults_merge.drop([0,"id"],axis=1, inplace=False)
# df_VFDB_CPR_DEG10_fiter_finallResults_merge

# process PATH

In [12]:
input_patric="/lomi_home/gaoyang/software/CompRanking/test/CompRanking/CompRanking_intermediate/Virulence/PATRIC/ERR1191817.contigs_5M_contigs_PATRIC.out"
df_patric=pd.read_csv(input_patric, sep="\t", header=None)
df_patric.columns=['id', 'sub_id', 'identity', 'alignLen', 'mismat', 'gapOpens', 'qStart', 'qEnd', 'sStart', 'sEnd', 'eval', 'bit']
df_patric

,id,sub_id,identity,alignLen,mismat,gapOpens,qStart,qEnd,sStart,sEnd,eval,bit
0,k119_8,CAFL01000023,99.188,985,8,0,1,985,45361,46345,0.000000e+00,1775.0
1,k119_8,ADUA01000365,99.287,982,7,0,4,985,9535,8554,0.000000e+00,1775.0
2,k119_8,ADUG01000028,99.287,982,7,0,4,985,8531,7550,0.000000e+00,1775.0
3,k119_8,JVHO01000071,99.287,982,7,0,4,985,61591,60610,0.000000e+00,1775.0
4,k119_8,JVAO01000010,99.287,982,7,0,4,985,61600,60619,0.000000e+00,1775.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8763035,k119_301781,KQ961444,72.698,315,74,9,134,442,16899,17207,5.610000e-15,95.3
8763036,k119_301781,JUYN01000043,72.642,318,75,9,134,445,2071,1760,5.610000e-15,95.3
8763037,k119_301781,CDEY01000015,72.698,315,74,9,134,442,43351,43659,5.610000e-15,95.3
8763038,k119_301781,CPWY01000015,82.524,103,16,2,113,214,42827,42726,2.610000e-13,89.8
8763039,k119_301781,NZ_AALF02000027,82.474,97,15,2,110,205,9164,9259,1.210000e-11,84.2

In [13]:
#iden60 and alen150
df_patric_iden60=df_patric[df_patric.identity > 80]
df_patric_den60_alen150=df_patric_iden60[df_patric_iden60.alignLen > 150]
df_patric_den60_alen150

,id,sub_id,identity,alignLen,mismat,gapOpens,qStart,qEnd,sStart,sEnd,eval,bit
0,k119_8,CAFL01000023,99.188,985,8,0,1,985,45361,46345,0.000000e+00,1775.0
1,k119_8,ADUA01000365,99.287,982,7,0,4,985,9535,8554,0.000000e+00,1775.0
2,k119_8,ADUG01000028,99.287,982,7,0,4,985,8531,7550,0.000000e+00,1775.0
3,k119_8,JVHO01000071,99.287,982,7,0,4,985,61591,60610,0.000000e+00,1775.0
4,k119_8,JVAO01000010,99.287,982,7,0,4,985,61600,60619,0.000000e+00,1775.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8763029,k119_301773,CSYV01000002,85.061,328,46,3,101,426,443510,443184,8.220000e-87,331.0
8763030,k119_301773,CSZD01000002,84.894,331,47,3,98,426,177955,178284,8.220000e-87,331.0
8763031,k119_301773,CSXJ01000004,85.061,328,46,3,101,426,490706,490380,8.220000e-87,331.0
8763032,k119_301773,CSXI01000001,84.894,331,47,3,98,426,260267,260596,8.220000e-87,331.0
8763033,k119_301781,FMGT01000035,80.388,464,84,7,1,461,29545,30004,1.400000e-90,346.0

In [14]:
df_PATH_contig=df_patric_den60_alen150[["id"]].drop_duplicates()
df_PATH_contig["Pathogenicity"]="Pathogenic"
df_PATH_contig

                  id Pathogenicity
0             k119_8    Pathogenic
500          k119_12    Pathogenic
505          k119_15    Pathogenic
538          k119_31    Pathogenic
1040         k119_35    Pathogenic
...              ...           ...
8761351  k119_301769    Pathogenic
8761361  k119_301770    Pathogenic
8761913  k119_301771    Pathogenic
8762414  k119_301773    Pathogenic
8763033  k119_301781    Pathogenic

[38465 rows x 2 columns]

# merge PATH-like sequence with VFs

In [22]:
#first merge VFs with index
df_VFs_contig=pd.merge(df_contig,df_VFDB_output_annote,left_on=1,right_on="id",how="left")
df_VFs_PATH_contig=pd.merge(df_VFs_contig,df_PATH_contig,left_on=0,right_on="id",how="left")
df_VFs_PATH_contig

,0,1,Contigs,id_x,sub_id,VFID,Virulence_factor,VF_Name,Bacteria,VFcategory,ESKAPE,id_y,Pathogenicity
0,k119_7,1_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,k119_8,2_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_8,Pathogenic
2,k119_12,3_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_12,Pathogenic
3,k119_12,3_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_12,Pathogenic
4,k119_14,4_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240330,k119_301780,123145_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240331,k119_301780,123145_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240332,k119_301781,123146_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_301781,Pathogenic
240333,k119_301781,123146_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_301781,Pathogenic
240334,k119_301781,123146_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,k119_301781,Pathogenic

In [23]:
#drop
df_VFs_PATH_contig=df_VFs_PATH_contig.drop(["Contigs","id_x","sub_id","VFID","id_y"],axis=1,inplace=False)
df_VFs_PATH_contig

,0,1,Virulence_factor,VF_Name,Bacteria,VFcategory,ESKAPE,Pathogenicity
0,k119_7,1_1,NaN,NaN,NaN,NaN,NaN,NaN
1,k119_8,2_1,NaN,NaN,NaN,NaN,NaN,Pathogenic
2,k119_12,3_1,NaN,NaN,NaN,NaN,NaN,Pathogenic
3,k119_12,3_2,NaN,NaN,NaN,NaN,NaN,Pathogenic
4,k119_14,4_1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
240330,k119_301780,123145_1,NaN,NaN,NaN,NaN,NaN,NaN
240331,k119_301780,123145_2,NaN,NaN,NaN,NaN,NaN,NaN
240332,k119_301781,123146_1,NaN,NaN,NaN,NaN,NaN,Pathogenic
240333,k119_301781,123146_2,NaN,NaN,NaN,NaN,NaN,Pathogenic
240334,k119_301781,123146_3,NaN,NaN,NaN,NaN,NaN,Pathogenic

In [24]:
#fill pathogenicity
df_VFs_PATH_contig=df_VFs_PATH_contig.fillna("-")
df_VFs_PATH_contig

,0,1,Virulence_factor,VF_Name,Bacteria,VFcategory,ESKAPE,Pathogenicity
0,k119_7,1_1,-,-,-,-,-,-
1,k119_8,2_1,-,-,-,-,-,Pathogenic
2,k119_12,3_1,-,-,-,-,-,Pathogenic
3,k119_12,3_2,-,-,-,-,-,Pathogenic
4,k119_14,4_1,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...
240330,k119_301780,123145_1,-,-,-,-,-,-
240331,k119_301780,123145_2,-,-,-,-,-,-
240332,k119_301781,123146_1,-,-,-,-,-,Pathogenic
240333,k119_301781,123146_2,-,-,-,-,-,Pathogenic
240334,k119_301781,123146_3,-,-,-,-,-,Pathogenic

In [25]:
for index ,name in df_VFs_PATH_contig.iterrows():
    if df_VFs_PATH_contig["Virulence_factor"][index] != "-":
        df_VFs_PATH_contig["Pathogenicity"][index]="Pathogenic"
df_VFs_PATH_contig

,0,1,Virulence_factor,VF_Name,Bacteria,VFcategory,ESKAPE,Pathogenicity
0,k119_7,1_1,-,-,-,-,-,-
1,k119_8,2_1,-,-,-,-,-,Pathogenic
2,k119_12,3_1,-,-,-,-,-,Pathogenic
3,k119_12,3_2,-,-,-,-,-,Pathogenic
4,k119_14,4_1,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...
240330,k119_301780,123145_1,-,-,-,-,-,-
240331,k119_301780,123145_2,-,-,-,-,-,-
240332,k119_301781,123146_1,-,-,-,-,-,Pathogenic
240333,k119_301781,123146_2,-,-,-,-,-,Pathogenic
240334,k119_301781,123146_3,-,-,-,-,-,Pathogenic

In [27]:
df_VFs_PATH_contig.columns=["Contig","ORF","Virulence_factor","VF_Name","VF_Host_Bacteria","VFcategory","ESKAPE","Pathogenicity"]
df_VFs_PATH_contig

,Contig,ORF,Virulence_factor,VF_Name,VF_Host_Bacteria,VFcategory,ESKAPE,Pathogenicity
0,k119_7,1_1,-,-,-,-,-,-
1,k119_8,2_1,-,-,-,-,-,Pathogenic
2,k119_12,3_1,-,-,-,-,-,Pathogenic
3,k119_12,3_2,-,-,-,-,-,Pathogenic
4,k119_14,4_1,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...
240330,k119_301780,123145_1,-,-,-,-,-,-
240331,k119_301780,123145_2,-,-,-,-,-,-
240332,k119_301781,123146_1,-,-,-,-,-,Pathogenic
240333,k119_301781,123146_2,-,-,-,-,-,Pathogenic
240334,k119_301781,123146_3,-,-,-,-,-,Pathogenic